import type { Metadata } from "next";
import { poppins } from "../styles/fonts";
import Link from "next/link";
import { LongArrowLeftSvg } from "../../../components/SvgGroup";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative flex min-h-screen w-full flex-col">
      <nav className="fixed flex h-16 w-full justify-between px-8 py-5 text-white/60">
        <div className="[&>*:hover]:text-white [&>*]:transition-all [&>*]:duration-300">
          <Link href={"/"}>
            <LongArrowLeftSvg className="h-8 w-8 stroke-current" />
          </Link>
        </div>
        <div className="flex gap-8 [&>*:hover]:text-white [&>*]:transition-all [&>*]:duration-300">
          <Link href={"/projects"}>Projects</Link>
          <Link href={"/about"}>About Me</Link>
          <Link href={"/contact"}>Contact</Link>
        </div>
      </nav>
      <main className="mx-auto mt-16 w-full max-w-[1280px] p-5">
        {children}
      </main>
    </div>
  );
}
